INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (1, 155, NULL, 'Cdoel', 'Collecte-doel, niet nader omschreven', 0, 1, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (2, 155, NULL, 'Cdoel_Diac', 'Collecte-doel: Diaconie', 0, 1, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (3, 155, NULL, 'Cdoel_Kerk', 'Collecte-doel: Kerk', 0, 1, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (4, 155, NULL, 'Cdoel_Bouw', 'Collecte-doel: Bouwfonds', 0, 1, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (5, 155, NULL, 'Alg_Uitgvn', 'Alg. uitgaven', 0, 2, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (6, 155, NULL, 'Adm_Alg', 'Algemene administratiekosten', 1, 3, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (7, 155, NULL, 'Adm_Bnkkst', 'Bankkosten', 1, 3, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (8, 155, NULL, 'Vwk_Alg', 'Algemene verwerkingskosten', 1, 4, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (9, 155, NULL, 'Vwk_Pzegel', 'Postzegels', 0, 4, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (10, 155, NULL, 'Vwk_Inkt', 'Inkt- en tonercardridges', 0, 4, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (11, 155, NULL, 'Vwk_Env', 'Enveloppen', 0, 4, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (12, 155, NULL, 'Vwk_Akpbon', 'Aankoop collectebonnen', 1, 4, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (13, 155, NULL, 'Vwk_Kntbnh', 'Kantoorbenodigdheden', 1, 4, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (14, 155, NULL, 'Adm_BnkING', 'Bankkosten - ING', 1, 3, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (15, 155, NULL, 'Adm_BnkRAB', 'Bankkosten - RABO', 1, 3, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (16, 155, NULL, 'Alg_Boekhk', 'Boekhoudkundige inkomsten/uitgaven', 1, 2, NULL, NULL);
INSERT INTO SubUitgavesoort (Sus_Id, Sus_StatusId, Sus_DispStatus, Sus_Kort, Sus_Lang, Sus_Wijzigentoegestaan, Sus_HusId, Sus_DispHus, Sus_Opmerking) values (17, 155, NULL, 'Alg_TvTw', 'Te veel of te weinig betaald voor collectebonnen', 1, 2, NULL, NULL);

