CREATE TABLE Bankgironr (
  Bgnr_Id INTEGER NOT NULL PRIMARY KEY Autoincrement,
  Bgnr_StatusId INTEGER DEFAULT 110009,
  Bgnr_DispStatus VARCHAR(75) DEFAULT 'Bankgironummergegevens zijn leeg / Tabel-initrecord',
  Bgnr_SysteemBgnr INTEGER DEFAULT 0,
  Bgnr_KLBgId INTEGER DEFAULT 1 NOT NULL,
  Bgnr_DispKlBg VARCHAR(75) DEFAULT 'Klant-Begunstigde',
  Bgnr_Tnv VARCHAR(50),
  Bgnr_Kort VARCHAR(9) DEFAULT '000000000' NOT NULL,
  Bgnr_Iban VARCHAR(18) DEFAULT 'NL59ONBB0000000000' NOT NULL,
  Bgnr_IbanBankGiroKas VARCHAR(1) DEFAULT 'I' NOT NULL,
  Bgnr_Opmerking VARCHAR(250),
  FOREIGN KEY (BGNR_STATUSID) REFERENCES STATUS(STATUS_CODE) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(BGNR_KLBGID) REFERENCES KLANT_BEGUNSTIGDE(KLBG_ID) ON DELETE CASCADE ON UPDATE CASCADE
);  
CREATE INDEX "IdxBgnr_KlBgId" ON Bankgironr (Bgnr_KLBgId ASC);
CREATE INDEX "IdxBgnr_Kort" ON Bankgironr (Bgnr_Kort ASC); 
CREATE INDEX "IdxBgnr_Iban" ON Bankgironr (Bgnr_Iban ASC);