CREATE TABLE SubUitgavesoort (
  Sus_Id INTEGER NOT NULL PRIMARY KEY Autoincrement,
  Sus_StatusId INTEGER DEFAULT 155009,
  Sus_DispStatus VARCHAR(75) DEFAULT 'Sus-record is leeg / Tabel-initrecord',
  Sus_Kort VARCHAR(10) DEFAULT 'Sus_kort' NOT NULL,
  Sus_Lang VARCHAR(50) DEFAULT 'Sus_lang' NOT NULL,
  Sus_Wijzigentoegestaan INTEGER DEFAULT 1,
  Sus_HusId INTEGER DEFAULT 1 NOT NULL,
  Sus_DispHus VARCHAR(50),
  Sus_Opmerking VARCHAR(250),
  FOREIGN KEY(SUS_STATUSID) REFERENCES STATUS(STATUS_CODE) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(SUS_HUSID) REFERENCES HOOFDUITGAVESOORT(HUS_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "IdxSus_Kort" ON SubUitgavesoort (Sus_Kort ASC); 
CREATE INDEX "IdxSus_HusId" ON SubUitgavesoort (Sus_HusId ASC);