INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (59, 140, 1, 0, 'Ugv-Status', '>> Uitgave-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (60, 140, 0, 1, 'Ugv-Nieuw', 'Nieuwe uitgave', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (61, 140, 0, 2, 'Ugv-Ingevoerd', 'Ingevoerde uitgave', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (62, 140, 0, 9, 'Ugv-Leeg', 'Uitgave-record is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (63, 145, 1, 0, 'Vwp-Status', '>> Vererkperiode-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (64, 145, 0, 1, 'Vwp-Nieuw', 'Nieuwe verwerkperode', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (65, 145, 0, 2, 'Vwp-Ingevoerd', 'Ingevoerde verwerkperiode', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (66, 145, 0, 9, 'Vwp-Leeg', 'Verwerkperiode-rec is zijn leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (67, 150, 1, 0, 'Vrrd-Status', '>> Voorraad-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (68, 150, 0, 1, 'Vrrd-Nieuw', 'Nieuwe voorraad', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (69, 150, 0, 2, 'Vrrd-Ingevoerd', 'Ingevoerde voorraad', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (70, 150, 0, 9, 'Vrrd-Leeg', 'Voorraad-record is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (71, 155, 1, 0, 'Sus-Status', '>> Sus-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (72, 155, 0, 1, 'Sus-Nieuw', 'Nieuw Sus-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (73, 155, 0, 2, 'Sus-Ingevoerd', 'Ingevoerd Sus-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (74, 155, 0, 9, 'Sus-Leeg', 'Sus-record is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (75, 160, 1, 0, 'Scat-Status', '>> Scat-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (76, 160, 0, 1, 'Scat-Nieuw', 'Nieuw Scat-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (77, 160, 0, 2, 'Scat-Ingevoerd', 'Ingevoerd Scat-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (78, 160, 0, 9, 'Scat-Leeg', 'Scat-record is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (79, 165, 1, 0, 'Saldostnd-Stat', '>> Saldostand-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (80, 165, 0, 1, 'Saldostnd-Nieuw', 'Nieuw Saldostand-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (81, 165, 0, 2, 'Saldostnd-Ingevoerd', 'Ingevoerd Saldostand-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (82, 165, 0, 9, 'Saldostnd-Leeg', 'Saldostand-record is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (83, 170, 1, 0, 'Prod-Stat', '>> Product-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (84, 170, 0, 1, 'Prod-Nieuw', 'Nieuw product-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (85, 170, 0, 2, 'Prod-Ingevoerd', 'Ingevoerd product-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (86, 170, 0, 9, 'Prod-Leeg', 'Product-record is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (87, 175, 1, 0, 'Licctrl-Stat', '>> Licctrl-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (88, 175, 0, 1, 'Licctrl-Nieuw', 'Nieuw licctrl-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (89, 175, 0, 2, 'Licctrl-Ingevoerd', 'Ingevoerd licctrl-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (90, 175, 0, 9, 'Licctrl-Leeg', 'Licctrl-record is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (91, 180, 1, 0, 'Jgeg-Stat', '>> Jgeg-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (92, 180, 0, 1, 'Jgeg-Nieuw', 'Nieuw jgeg-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (93, 180, 0, 2, 'Jgeg-Ingevoerd', 'Ingevoerd jgeg-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (94, 180, 0, 9, 'Jgeg-Leeg', 'Jgeg-record is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (95, 185, 1, 0, 'Instl-Stat', '>> Instl-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (96, 185, 0, 1, 'Instl-Nieuw', 'Nieuw instl-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (97, 185, 0, 2, 'Instl-Ingevoerd', 'Ingevoerd instl-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (98, 185, 0, 9, 'Instl-Leeg', 'Instl-record is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (99, 190, 1, 0, 'Hus-Stat', '>> Hus-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (100, 190, 0, 1, 'Hus-Nieuw', 'Nieuw hus-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (101, 190, 0, 2, 'Hus-Ingevoerd', 'Ingevoerd hus-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (102, 190, 0, 9, 'Hus-Leeg', 'Hus-record is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (103, 195, 1, 0, 'Hcat-Stat', '>> Hcat-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (104, 195, 0, 1, 'Hcat-Nieuw', 'Nieuw hcat-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (105, 195, 0, 2, 'Hcat-Ingevoerd', 'Ingevoerd hcat-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (106, 195, 0, 9, 'Hcat-Leeg', 'Hcat-record is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (107, 200, 1, 0, 'Emladrs-Stat', '>> Emladrs-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (108, 200, 0, 1, 'Emladrs-Nieuw', 'Nieuw emladrs-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (109, 200, 0, 2, 'Emladrs-Ingevoerd', 'Ingevoerd emladrs-record', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (110, 200, 0, 9, 'Emladrs-Leeg', 'Emladrs-record is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (1, 1, 1, 0, 'Gebr-Status', '>> Gebruiker-statusgroep', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (2, 1, 0, 1, 'Gebr-Actief', 'Actieve, normale gebruiker', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (3, 1, 0, 5, 'Gebr-System', 'Systeem-gebruiker', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (4, 1, 0, 9, 'Gebr-Demo', 'Demo-gebruiker', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (5, 10, 1, 0, 'KlBg-Status', '>> Klant-Begunstigde-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (6, 10, 0, 1, 'KlBg-Actief', 'Actief', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (7, 10, 0, 2, 'KlBg-Overleden', 'Overleden', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (8, 10, 0, 3, 'KlBg-Vertrokken', 'Vertrokken of eventueel onttrokken', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (9, 10, 0, 9, 'KlBg-Onbekend', 'Onbekende status / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (10, 20, 1, 0, 'Adres-Status', '>> Adres-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (11, 20, 0, 1, 'Adres-Actief', 'Actief gebruikt bij Klant-Begunstigde', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (12, 20, 0, 2, 'Adres-Ingevoerd', 'Ingevoerd, maar niet actief bij Klant-Begunstigde', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (13, 20, 0, 9, 'Adres-Leeg', 'Adresgegevens zijn leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (14, 50, 1, 0, 'Progpart', '>> Programma-onderdeel', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (15, 50, 1, 1, 'Progpart-Onbekend', 'Programmadeelnaam onbekend', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (16, 50, 0, 2, 'Progpart-DtmdlCbp', 'Datamodel Cbp', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (17, 50, 0, 3, 'Progpart-Cbp_ELicen', 'Licentie-programma', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (18, 55, 1, 0, 'Errcd', '>> Errorcodes', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (19, 55, 0, 1, 'Errcd-Onb', 'Onbekende, ongedefinieerde fout', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (20, 55, 0, 2, 'Errcd-Waarde_0', 'Waarde mag geen 0 zijn', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (21, 55, 0, 3, 'Errcd-Tabel_close', 'Tabel niet geopend', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (22, 100, 1, 0, 'Lic-Type', '>> Licentie-type', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (23, 100, 0, 1, 'Lic-Actief', 'Licentie-actief', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (24, 100, 0, 9, 'Lic-Demo', 'Licentie-demo', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (25, 105, 1, 0, 'Telnr-Status', '>> Telnr-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (26, 105, 0, 1, 'Telnr-Actief', 'Actief gebruikt bij Klant-Begunstigde', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (27, 105, 0, 2, 'Telnr-Ingevoerd', 'Ingevoerd, maar niet actief bij Klant-Begunstigde', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (28, 105, 0, 9, 'Telnr-Leeg', 'Telefoonnummergegevens zijn leeg / Tabel-initrecor', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (29, 110, 1, 0, 'Bgnr-Status', '>> Bgnr-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (30, 110, 0, 1, 'Bgnr-Actief', 'Actief gebruikt bij Klant-Begunstigde', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (31, 110, 0, 2, 'Bgnr-Ingevoerd', 'Ingevoerd, maar niet actief bij Klant-Begunstigde', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (32, 110, 0, 9, 'Bgnr-Leeg', 'Bankgironummergegevens zijn leeg / Tabel-initrecor', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (33, 115, 1, 0, 'Eml-Status', '>> Email-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (34, 115, 0, 1, 'Eml-Actief', 'Actief gebruikt bij Klant-Begunstigde', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (35, 115, 0, 2, 'Eml-Ingevoerd', 'Ingevoerd, maar niet actief bij Klant-Begunstigde', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (36, 115, 0, 9, 'Eml-Leeg', 'E-mailgegevens zijn leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (37, 120, 1, 0, 'Bstl-Status', '>> Bestelling-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (38, 120, 0, 1, 'Bstl-Ingevoerd', 'Ingevoerde bestelling', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (39, 120, 0, 9, 'Bstl-Leeg', 'Bestelling is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (40, 125, 1, 0, 'Bnkrgl-Status', '>> Bankregel-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (41, 125, 0, 1, 'Bnkrgl-Ingevoerd', 'Ingevoerde bankregel', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (42, 125, 0, 9, 'Bnkrgl-Leeg', 'Bankregel is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (43, 130, 1, 0, 'Log-Status', '>> Logregel-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (44, 130, 0, 1, 'Log-Nieuw', 'Nieuwe log-regel', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (45, 130, 0, 2, 'Log-Gewijzigd', 'Gewijzigde log-regel', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (46, 130, 0, 9, 'Log-Leeg', 'Logregel is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (47, 121, 1, 0, 'Bstl-Div-Status', '>> Bestelling-diversen-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (48, 121, 0, 1, 'Bstl-Div-Nieuw', 'Nieuwe bestelling-diversen-regel', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (49, 121, 0, 2, 'Bstl_Div-Ingevoerd', 'Ingevoerde bestelling-diversen-regel', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (50, 121, 0, 9, 'Bstl_Div-Leeg', 'Bestelling-diversen-regel leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (51, 122, 1, 0, 'Bstl-Vschl-Status', '>> Bestelling-verschil-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (52, 122, 0, 1, 'Bstl_Vschl-Nieuw', 'Nieuwe bestelling-verschil-regel', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (53, 122, 0, 2, 'Bstl_Vschl-Ingevoerd', 'Ingevoerde bestelling-verschil-regel', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (54, 122, 0, 9, 'Bstl_Vschl-Leeg', 'Bestelling-verschil-reg is leeg / Tabel-initrecord', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (55, 135, 1, 0, 'Bstlr-Status', '>> Bestelregel-status', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (56, 135, 0, 1, 'Bstlr-Nieuw', 'Nieuwe bestelregel', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (57, 135, 0, 2, 'Bstlr-Ingevoerd', 'Ingevoerde bestelregel', NULL);
INSERT INTO Status (StatusId, Status_Groep, Status_Hoofdgroepitem, Status_Nr, Status_Kort, Status_Lang, Opmerking) values (58, 135, 0, 9, 'Bstlr-Leeg', 'Bestelregel is leeg / Tabel-initrecord', NULL);