DROP TABLE Sets;
CREATE TABLE Sets (
  Usermode BYTE DEFAULT 1 NOT NULL
);
INSERT INTO Sets (Usermode) values (5);
INSERT INTO Sets (Usermode) values (2);
INSERT INTO Sets (Usermode) values (3);
INSERT INTO Sets (Usermode) values (4);
INSERT INTO Sets (Usermode) values (5);
INSERT INTO Sets (Usermode) values (6);
INSERT INTO Sets (Usermode) values (7);
INSERT INTO Sets (Usermode) values (8);
INSERT INTO Sets (Usermode) values (9);

